In [11]:
import numpy as np

In [12]:
lista = [1,2,3,4,5]
lista_array = np.array(lista) #per passare da lista ad array usi il costruttore 
lista

[1, 2, 3, 4, 5]

In [13]:
lista_array #non è una lista, è un array numpy
#anche per python sono oggetti diversi

array([1, 2, 3, 4, 5])

In [14]:
#np.zeros?per ottenere la documentazione sul metodo 
np.zeros(10, dtype=int) #array lungo 10 di tipo float di default, se lo specifichi diventa il tipo che dici


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((5,10), dtype=float) #matrice di 0, np.ones = array di 1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,1)) #le ia imparano con dati a molte dimensioni, per es nella tesla tutto ciò che riceve finisce in una matrice 

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [17]:
np.random.uniform() #numeri che si comportano come casuali, ma generati da un altgorimo deterministico, anche se 
                  #apparentemente sembrano casuali
                  #calculus, libreria che serve per calcolare derivate e integrali

0.8546439110565583

In [18]:
np.random.uniform(size = 100) #array di 100 numeri casuali, sempre numeri float

array([0.40889212, 0.3817176 , 0.27246935, 0.23639009, 0.59152317,
       0.83228341, 0.49181706, 0.83200093, 0.97385518, 0.23149167,
       0.0578576 , 0.58545788, 0.06714588, 0.55200577, 0.39237748,
       0.224768  , 0.63970519, 0.90557831, 0.06070681, 0.39391666,
       0.03740532, 0.78357953, 0.39106618, 0.8763298 , 0.08562941,
       0.20415807, 0.17156433, 0.13280203, 0.70938521, 0.93508258,
       0.42564447, 0.41323661, 0.41462958, 0.85075202, 0.23255327,
       0.48677399, 0.85158587, 0.3464536 , 0.66550494, 0.66320414,
       0.74617955, 0.56860899, 0.90433117, 0.6508385 , 0.25212842,
       0.549527  , 0.97201017, 0.38495893, 0.10223187, 0.08053131,
       0.95326721, 0.20535896, 0.42308411, 0.08306066, 0.12304192,
       0.29636545, 0.97048211, 0.67481723, 0.2929844 , 0.71195983,
       0.56519536, 0.8025168 , 0.78939892, 0.0363992 , 0.71774023,
       0.78041203, 0.70055847, 0.10413192, 0.40510019, 0.77293089,
       0.368028  , 0.99594209, 0.83172914, 0.64113612, 0.84402

In [19]:
np.random.normal(size = 100) #distribuzione gaussiana

array([ 0.77181827,  2.34320722, -0.0875455 , -2.31253314,  0.60298684,
       -0.63438058,  0.80455238, -0.34483773,  0.63094261,  0.6228273 ,
       -0.08071125, -0.77156753,  0.22864126, -0.62781238, -1.87887145,
        0.17884412, -2.10996115,  1.15884936,  0.96669351, -1.85435055,
       -0.09940964, -0.6142827 , -0.69307895, -0.37367999, -1.06349612,
       -2.12036264, -1.32249102, -1.48627913, -0.27660993, -1.54010699,
        0.43950741,  0.47795769, -0.20578376,  0.54590296, -1.24593343,
        2.41241832,  1.21720085, -0.53471437,  1.34731878, -0.99138248,
       -1.63763217,  0.20721932,  0.36379146, -0.83424203,  0.61882931,
        0.44737149, -0.75088822,  1.22178284, -0.88398406, -0.15176012,
        1.55174693, -0.34146331,  0.31684762, -0.78566868,  0.81894344,
        0.76958515,  0.9679384 , -0.59936654,  0.77904838, -0.64092212,
       -1.95216894, -1.54712349,  0.49986285, -1.34689406,  1.66501381,
       -0.36528542,  0.50335863, -0.85253614, -0.45510951, -1.03

In [20]:
np.random.normal(loc = 5, scale = 1, size = 100)

array([5.39996434, 5.18657827, 5.85473378, 4.69061175, 3.50548069,
       4.60998254, 4.65237709, 5.67066818, 4.87602582, 4.64795877,
       5.02544805, 4.83925862, 3.47503978, 5.29328213, 6.22231156,
       3.54191129, 6.43436452, 4.51446787, 4.78426275, 4.74273509,
       5.28217733, 5.20480277, 3.16509425, 3.28198393, 4.91228106,
       4.1336188 , 4.78399481, 4.68470289, 4.42542012, 5.30801604,
       3.79621848, 4.7544655 , 5.2558523 , 5.97217344, 5.27883355,
       4.68066028, 3.95114718, 6.07224489, 4.87183239, 6.21395253,
       6.03442267, 6.20068846, 5.77313541, 4.79340963, 4.86465356,
       3.59362275, 4.25831202, 3.67422778, 6.55178831, 5.71653111,
       4.46715353, 5.1875556 , 3.81913064, 4.89190367, 4.41039469,
       4.73024511, 6.87544981, 4.15100352, 3.83740448, 5.22500405,
       5.03347859, 5.81190792, 5.71905792, 6.00465843, 6.45008011,
       3.21942403, 3.7675646 , 5.55957773, 3.86265861, 3.82913733,
       6.32960938, 4.19068954, 3.85054247, 6.77335376, 5.00670

In [21]:
np.random.random_integers(low=1,high=6,size=10) #simula lanci del dado, high è compreso, pure low, e sono distribuiti
                                                #in maniera uniforme

<ipython-input-21-8dd1f25e7908>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  np.random.random_integers(low=1,high=6,size=10) #simula lanci del dado, high è compreso, pure low, e sono distribuiti


array([3, 5, 1, 4, 6, 3, 4, 3, 4, 2])

In [31]:
np.random.choice(("ciao", "addio"))

'ciao'

In [32]:
matrice = np.random.uniform(size=(4,5))   
np.shape(matrice)

(4, 5)

In [33]:
vettore = np.array([1,2,3,4,5])
np.shape(vettore)

(5,)

In [34]:
vettore

array([1, 2, 3, 4, 5])

In [35]:
np.size(vettore)

5

In [41]:
lanci_dado = np.random.randint(1,7,10000)
lanci_dado2 = np.random.randint(1,7,10000)
print(lanci_dado)

[3 2 3 ... 4 3 6]


In [42]:
lanci_dado == 6

array([False, False, False, ..., False, False,  True])

In [43]:
np.count_nonzero(lanci_dado>=4)/10000

0.5036

In [44]:
1/6

0.16666666666666666

In [45]:
lanci_dado + lanci_dado2 == 8

array([False, False, False, ..., False,  True, False])

In [46]:
np.count_nonzero(lanci_dado + lanci_dado2 > 6)/10000

0.5878