In [50]:
import numpy as np
import random
import uuid

### Broadcast

In [51]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
b = a.reshape((-1,11))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [54]:
c = np.ones(11)*100
c

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [55]:
b+c

array([[100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.]])

## termoscanner

In [69]:
n_passeggeri = 2000000
Temperature = np.random.normal(36.5,0.25,n_passeggeri)
identificativi = np.array([str(uuid.uuid4()) for _ in range(n_passeggeri)])
for i, t in zip(identificativi, Temperature):
    if t > 37.5:
        print(f"passeggero: {i}, di temperatura: {t}" )

passeggero: f036e873-74d1-4492-a508-238fd175fa9d, di temperatura: 37.51569215334492
passeggero: 2977de5c-9585-4374-b8ed-e9a5ae728f1a, di temperatura: 37.502495315424376
passeggero: 384b220d-c75d-4749-953f-81a840da3c16, di temperatura: 37.54893921235039
passeggero: fe896feb-69e1-423e-bc58-5231a254ad6e, di temperatura: 37.5014352301527
passeggero: 95812ad1-de5a-4e6d-8c82-47cf62a516e9, di temperatura: 37.57802453700224
passeggero: dd46a894-b01d-4b50-9bf7-e2f049f88293, di temperatura: 37.54922778000389
passeggero: c302b288-de68-4dfe-9270-e744ca767114, di temperatura: 37.50697369018059
passeggero: 3b3e5044-c2a7-4c1f-8539-8b714929969f, di temperatura: 37.59148438995256
passeggero: a243b536-993d-47cb-a44c-3f348d602e02, di temperatura: 37.55516755984711
passeggero: 2eb9cc81-8254-41fc-a068-146f7d008551, di temperatura: 37.55039505602166
passeggero: 1efd92eb-ae99-4f67-b743-ed0d8f8b0a01, di temperatura: 37.51085340118686
passeggero: 0c9e4f23-5307-4742-bc31-d30d819f56f3, di temperatura: 37.5931969

In [70]:
print(np.count_nonzero(Temperature > 37.5))

75


In [71]:
print(identificativi[Temperature > 37.5])

['f036e873-74d1-4492-a508-238fd175fa9d'
 '2977de5c-9585-4374-b8ed-e9a5ae728f1a'
 '384b220d-c75d-4749-953f-81a840da3c16'
 'fe896feb-69e1-423e-bc58-5231a254ad6e'
 '95812ad1-de5a-4e6d-8c82-47cf62a516e9'
 'dd46a894-b01d-4b50-9bf7-e2f049f88293'
 'c302b288-de68-4dfe-9270-e744ca767114'
 '3b3e5044-c2a7-4c1f-8539-8b714929969f'
 'a243b536-993d-47cb-a44c-3f348d602e02'
 '2eb9cc81-8254-41fc-a068-146f7d008551'
 '1efd92eb-ae99-4f67-b743-ed0d8f8b0a01'
 '0c9e4f23-5307-4742-bc31-d30d819f56f3'
 '2c5d1f5f-3b6b-466b-b50f-77fd07d381a5'
 '1b98f8dd-a0c4-46b4-9d40-69c2c7be3fc0'
 'ab8681f6-1431-4a2a-bf14-c11207d40b0d'
 'c661b130-bf0f-4fcf-9c61-4ac3d4ec9b2e'
 '47b8f712-e0ce-4bc4-bc1e-9fd8b44a1c11'
 '53a43b9e-a6a3-4724-84a8-89da063b42f7'
 '18ab14af-0b02-4c21-97b1-f0fd2af119a2'
 '5737b44d-c102-49f2-b6db-c13d3fe11cbf'
 'f0e3e029-e937-4985-bcbc-3f6a1f18b249'
 'ec263245-b1ed-4897-b8f4-cc91f8ad4a70'
 'da04fc7f-da5a-4035-8edd-ed7545971475'
 '410d519e-ccc8-4682-a42e-546631b634c8'
 '524ea1ca-2de7-4b5f-a103-68571215f20b'


In [72]:
cont = 0
for t in Temperature:
    if t > 37.5:
        cont += 1
    

In [74]:
%%timeit
np.count_nonzero(Temperature > 37.5)

2.04 ms ± 42.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
