In [1]:
import numpy as np


# esercizio 1

In [4]:
import numpy as np
import random as rnd

secondo = 1
minuto = 60 * secondo
ora = minuto * 60
giorno = ora * 24
tempo = giorno * 5

tempo

432000

# esercizio 2

In [2]:
a = np.random.choice([-1,1], 432000)
b = np.cumsum(a)
b = -1    

In [3]:
classi = 1000
num_studenti = 25
mat = np.array([1000, 25])
mat

array([1000,   25])

### esercizio 3


In [7]:
import numpy as np

def PuntiMassimo(n, arr): 
  
    mx = [] 
    for i in range(1, n-1): 
        if(arr[i-1] < arr[i] > arr[i + 1]): 
            mx.append(i) 
  
 # stampo i massimi
    if(len(mx) > 0): 
        print("punti di massimo : ") 
        print(mx) 
  
   
if __name__ == '__main__': 
  
    N = 6
    arr = np.array([0,2,1,1,3,2]) 
  
    PuntiMassimo(N, arr)

punti di massimo : 
[1, 4]


### 

# esercizio 4

In [5]:
import numpy as np
a = np.random.random_integers(low=0,high=9, size=12)
print(a)

indice=np.where(np.isin(a,[1,2,3]))
np.roll(a, -1)

np.roll(a, 1)


print(indice)


[0 2 0 1 8 2 4 3 1 3 4 2]
(array([ 1,  3,  5,  7,  8,  9, 11], dtype=int64),)


C:\Users\aledu\AppData\Local\Temp/ipykernel_15760/3064496386.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  a = np.random.random_integers(low=0,high=9, size=12)


# esercizio 5

In [6]:
import random
num_minuti = 24*60
valore_0_1_non_percentuale = 1/100
valore_0_2_non_percentuale = 1/200
def num_random(a):
    val = np.random.random()
    if val < valore_0_1_non_percentuale:
        return 9999
    elif val < valore_0_2_non_percentuale:
        return -1
    else:
        return np.random.randint(0,40)
    
