In [1]:
import numpy as np

1)Creare una funzione che inverta un ndarray monodimensionale, ovvero crei un array monodimensionale con gli stessi elementi dell'array di partenza in ordine inverso.

In [10]:
a = np.random.normal(size = 10)
a

array([ 1.4222957 ,  1.00561488,  0.39312315, -0.96262719,  1.21243243,
       -0.86088234,  1.51217494,  2.19678562, -0.82509114,  0.82121032])

In [11]:
a_inv = a[::-1]
a_inv

array([ 0.82121032, -0.82509114,  2.19678562,  1.51217494, -0.86088234,
        1.21243243, -0.96262719,  0.39312315,  1.00561488,  1.4222957 ])

2)Generare un array Numpy che contenga le posizioni dei primi 100 numeri primi all'interno dei numeri naturali.

In [31]:
def isprime(n):
    ret = True
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            ret = False
            break
    return ret
isprime_v = np.vectorize(isprime)

In [50]:
natural_n = np.arange(2,1000)
(natural_n[isprime_v(natural_n)]+1)[:100]

array([  3,   4,   6,   8,  12,  14,  18,  20,  24,  30,  32,  38,  42,
        44,  48,  54,  60,  62,  68,  72,  74,  80,  84,  90,  98, 102,
       104, 108, 110, 114, 128, 132, 138, 140, 150, 152, 158, 164, 168,
       174, 180, 182, 192, 194, 198, 200, 212, 224, 228, 230, 234, 240,
       242, 252, 258, 264, 270, 272, 278, 282, 284, 294, 308, 312, 314,
       318, 332, 338, 348, 350, 354, 360, 368, 374, 380, 384, 390, 398,
       402, 410, 420, 422, 432, 434, 440, 444, 450, 458, 462, 464, 468,
       480, 488, 492, 500, 504, 510, 522, 524, 542])

3)Generare un array Numpy contenente i primi 10 numeri di Fibonacci

In [48]:
n = 11
start = np.ones(11,dtype=int)
for i in range(2,n):
    start[i]=start[i-1]+start[i-2]
start[1:]

array([ 1,  2,  3,  5,  8, 13, 21, 34, 55, 89])