In [1]:
import numpy as np

# esercizio 1

In [4]:
mat_bin = np.zeros(shape = (8, 8))
for i in range(8):
    for j in range(8):
        if i%2 == 0:
            if j%2 == 1:
                mat_bin[i][j] = 1
            else:
                mat_bin[i][j] = 0
        else :
            if c%2 == 0:
                mat_bin[i][j] = 1
            else:
                mat_bin[i][j] = 0
print(mat_bin)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# esercizio 2

In [8]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
array2 = []
for a in range(len(array)-3):
    array2.append((array[a], array[a+1], array[a+2], array[a+3]))

arr = np.array(array2, np.uint8)

print(arr)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# esercizio 3

In [11]:
num_classe = int(input("Numero compagni di classe: "))
minimo = float(np.random.randint(140, 150))
massimo = float(np.random.randint(190, 200))

centro = float(np.random.randint(minimo, massimo))
scala = 10
classe = np.random.normal(centro, scala, num_classe)



classe

Numero compagni di classe: 3


array([159.06084232, 174.29272361, 166.53725314])