In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
b = arr[1:4] 
b[...] = 99
print(b)
arr

[99 99 99]


array([ 1, 99, 99, 99,  5])

# Fancy indexing


In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
b = arr[[True,False,True,False,True]]
b

array([1, 3, 5])

In [6]:
b.base in arr

False

esempio

In [7]:
dadoAlice = np.random.randint(1,7,10)
dadoBob = np.random.randint(1,7,10)
print(dadoAlice)
print(dadoBob)

[5 5 6 1 5 4 3 6 2 3]
[2 3 3 6 2 4 5 3 3 3]


In [8]:
dado1 = np.random.randint(1,7,10)

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
mat = np.array([[1,2,3], [3,4,5], [5,6,7]])
mat

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [11]:
mat[2][0]  #per prendere l'elemento nella prima colonna nella terza riga

5

In [12]:
terza_colonna = mat[:,0]  #per prendere la prima colonna
terza_colonna

array([1, 3, 5])

In [13]:
terza_colonna[...] = 2  # per scrivere 2 su tutta la prima colonna
terza_colonna

array([2, 2, 2])

In [14]:
mat

array([[2, 2, 3],
       [2, 4, 5],
       [2, 6, 7]])

In [15]:
mat = np.random.randint(0,2, size=(10,10))
mat

array([[1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0, 0, 0]])